version: '3'

services:
  python-app:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - python-app
