services:
  python-app:
    build: .
    ports:
      - "8089:5000"
    resources:
      reservations:
        memory: 1.5g


# 注释掉 Nginx 相关的部分
#  nginx:
#    image: nginx:latest
#    ports:
#      - "8089:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - python-app
