version: '3'

services:
  python-app:
    build: .
    ports:
      - "8089:8089"

  nginx:
    image: nginx:latest
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python-app
