version: '3'

services:
  python-app:
    build: .
    ports:
      - "5000:5000"

# 注释掉 Nginx 相关的部分
  nginx:
    image: nginx:latest
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python-app
