version: '3'

services:
  python-app:
    build: .
    ports:
      - "5000:8089"  # 将容器的5000端口映射到主机的8089端口

  nginx:
    image: nginx:latest
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python-app
